Created README.md
dil-classroom/projet-louis_mondaini_nunez pull request #9
Opened 2022-03-03 12:51 UTC by damianomondaini

Resolves #1

2022-03-03 12:56 UTC, hadrylouis requested changes
Please work more !

2022-03-03 12:56 UTC, hadrylouis commented on README.md
> +# Title placeholder
Please enter a valid readme.md file

2022-03-03 12:59 UTC, damianomondaini commented on README.md
> +# Title placeholder
Ok I did it.

2022-03-10 10:49 UTC, NunezTania commented on README.md
> +1. [Description](#description)
Lien non fonctionnel

2022-03-10 10:50 UTC, NunezTania requested changes
Lien en début de fichier à fix

2022-03-10 10:59 UTC, NunezTania approved these changes

2022-03-10 11:27 UTC, hadrylouis approved these changes

2022-03-10 11:30 UTC, merged